# version: "3.9"
# services:
#   web:
#     build: .
#     ports:
#       - "8080:8080"
#     volumes:
#       - .:/app
# version: "3.9"
# services:
#   web:
#     build: .
#     command: python -u imageserver.py
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/app
#     links:
#       - db
#   db:
#     image: mongo:latest
#     # command: ./mybashscript.sh

#     ports:
#       - 27017:27017

version: '3.4'

services:
  docker_flask_mongo:
    build: .
    ports:
      - '5000:5000'

  mongodb:
    image: mongo:3.4
    ports:
      - '27017:27017'